//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOANCNPM_VER1.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=TIEUQUYNH\\TIEUNGU;Initial Catalog=QuanLyDaiLy123;Integrated Security=" +
            "True")]
        public string QuanLyDaiLy123ConnectionString {
            get {
                return ((string)(this["QuanLyDaiLy123ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=TIEUQUYNH\\TIEUNGU;Initial Catalog=\"D:\\HOC KY 6\\PHÁT TRIỂN, VẬN HÀNH, " +
            "BẢO TRÌ PHẦN MỀM\\DOANCNPM_VER3\\FILE SQL\\QUANLYDAILY1.MDF\";Integrated Security=Tr" +
            "ue")]
        public string D__HOC_KY_6_PHÁT_TRIỂN__VẬN_HÀNH__BẢO_TRÌ_PHẦN_MỀM_DOANCNPM_VER3_FILE_SQL_QUANLYDAILY1_MDFConnectionString {
            get {
                return ((string)(this["D__HOC_KY_6_PHÁT_TRIỂN__VẬN_HÀNH__BẢO_TRÌ_PHẦN_MỀM_DOANCNPM_VER3_FILE_SQL_QUANLYD" +
                    "AILY1_MDFConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DUYTHANH-PC;Initial Catalog=QuanLyDaiLy123;Integrated Security=True")]
        public string QuanLyDaiLy123ConnectionString1 {
            get {
                return ((string)(this["QuanLyDaiLy123ConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=NAMHOANG;Initial Catalog=QuanLyDaiLy;Integrated Security=True")]
        public string QuanLyDaiLyConnectionString {
            get {
                return ((string)(this["QuanLyDaiLyConnectionString"]));
            }
        }
    }
}
